CREATE OR ALTER TABLE AIRFLOW_PILOT.COUNTRIES.CURATED_COUNTRIES
(
    COUNTRY_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1, // Pseudo ID. not actual primary key.
    LOAD_ID NUMBER, // Original load ID.
    COMMON_COUNTRY_NAME VARCHAR(1000),
    OFFICIAL_COUNTRY_NAME VARCHAR(1000),
    ALPHA3_CODE VARCHAR(1000),
    CCN3_NUMERIC_CODE VARCHAR(1000),
    CURRENCY VARCHAR(1000),
    GOOGLE_MAPS_URL VARCHAR(1000),
    OFFICIAL_LINK VARCHAR(1000),
    WIKIPEDIA_LINK VARCHAR(1000),
    TIMEZONES VARCHAR(1000),
    LANGUAGES VARCHAR(1000),
    INSERTED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    INSERTED_USER VARCHAR(1000) DEFAULT CURRENT_USER(),
    LAST_UPDATE_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_UPDATE_USER VARCHAR(1000) DEFAULT CURRENT_USER()
)
COMMENT = 'Curated table for countries data';