MERGE INTO AIRFLOW_PILOT.COUNTRIES.CURATED_COUNTRIES AS target
USING (
    SELECT
        LOAD_ID,
        COMMON_COUNTRY_NAME,
        OFFICIAL_COUNTRY_NAME,
        ALPHA3_CODE,
        CCN3_NUMERIC_CODE,
        CURRENCY,
        GOOGLE_MAPS_URL,
        OFFICIAL_LINK,
        WIKIPEDIA_LINK,
        TIMEZONES,
        LANGUAGES
    FROM AIRFLOW_PILOT.COUNTRIES.STG_COUNTRIES
    WHERE ALPHA3_CODE IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY ALPHA3_CODE
        ORDER BY LOAD_ID DESC
    ) = 1
) AS incoming
    ON target.COMMON_COUNTRY_NAME = incoming.COMMON_COUNTRY_NAME
WHEN MATCHED AND (
    target.COMMON_COUNTRY_NAME IS DISTINCT FROM incoming.COMMON_COUNTRY_NAME
    OR target.OFFICIAL_COUNTRY_NAME IS DISTINCT FROM incoming.OFFICIAL_COUNTRY_NAME
    OR target.CCN3_NUMERIC_CODE IS DISTINCT FROM incoming.CCN3_NUMERIC_CODE
    OR target.CURRENCY IS DISTINCT FROM incoming.CURRENCY
    OR target.GOOGLE_MAPS_URL IS DISTINCT FROM incoming.GOOGLE_MAPS_URL
    OR target.OFFICIAL_LINK IS DISTINCT FROM incoming.OFFICIAL_LINK
    OR target.WIKIPEDIA_LINK IS DISTINCT FROM incoming.WIKIPEDIA_LINK
    OR target.TIMEZONES IS DISTINCT FROM incoming.TIMEZONES
    OR target.LANGUAGES IS DISTINCT FROM incoming.LANGUAGES
)
THEN UPDATE SET
    target.LOAD_ID = incoming.LOAD_ID,
    target.COMMON_COUNTRY_NAME = incoming.COMMON_COUNTRY_NAME,
    target.OFFICIAL_COUNTRY_NAME = incoming.OFFICIAL_COUNTRY_NAME,
    target.CCN3_NUMERIC_CODE = incoming.CCN3_NUMERIC_CODE,
    target.CURRENCY = incoming.CURRENCY,
    target.GOOGLE_MAPS_URL = incoming.GOOGLE_MAPS_URL,
    target.OFFICIAL_LINK = incoming.OFFICIAL_LINK,
    target.WIKIPEDIA_LINK = incoming.WIKIPEDIA_LINK,
    target.TIMEZONES = incoming.TIMEZONES,
    target.LANGUAGES = incoming.LANGUAGES,
    target.LAST_UPDATE_TS = CURRENT_TIMESTAMP(),
    target.LAST_UPDATE_USER = CURRENT_USER()
WHEN NOT MATCHED THEN INSERT
    (
        LOAD_ID,
        COMMON_COUNTRY_NAME,
        OFFICIAL_COUNTRY_NAME,
        ALPHA3_CODE,
        CCN3_NUMERIC_CODE,
        CURRENCY,
        GOOGLE_MAPS_URL,
        OFFICIAL_LINK,
        WIKIPEDIA_LINK,
        TIMEZONES,
        LANGUAGES
    )
    VALUES
    (
        incoming.LOAD_ID,
        incoming.COMMON_COUNTRY_NAME,
        incoming.OFFICIAL_COUNTRY_NAME,
        incoming.ALPHA3_CODE,
        incoming.CCN3_NUMERIC_CODE,
        incoming.CURRENCY,
        incoming.GOOGLE_MAPS_URL,
        incoming.OFFICIAL_LINK,
        incoming.WIKIPEDIA_LINK,
        incoming.TIMEZONES,
        incoming.LANGUAGES
    );