CREATE OR REPLACE TABLE AIRFLOW_PILOT.COUNTRIES.RAW_COUNTRIES
(
    LOAD_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    RAW_DATA VARIANT,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LOAD_USER VARCHAR(1000) DEFAULT CURRENT_USER()
)
COMMENT = 'Raw data from RESTCOUNTRIES API';