CREATE OR ALTER TABLE AIRFLOW_PILOT.COUNTRIES.STG_COUNTRIES
(
    LOAD_ID NUMBER,
    COMMON_COUNTRY_NAME VARCHAR(1000),
    OFFICIAL_COUNTRY_NAME VARCHAR(1000),
    ALPHA3_CODE VARCHAR(1000),
    CCN3_NUMERIC_CODE VARCHAR(1000),
    CURRENCY VARCHAR(1000),
    GOOGLE_MAPS_URL VARCHAR(1000),
    OFFICIAL_LINK VARCHAR(1000),
    WIKIPEDIA_LINK VARCHAR(1000),
    TIMEZONES VARCHAR(1000),
    LANGUAGES VARCHAR(1000)
)
COMMENT = 'Staging table for countries data';